on: [push]

jobs:
  hello_world_job:
  runs-on: ubuntu-latest
  steps:
    - name: Hello world action step
    uses: actions/mattmurp/github-action-test@v1
    with:
    who-to-greet: 'Matt'
    - name: Get the output time
    run: echo "The time was ${{ steps.hello.outputs.time }}"

